sudo: false
language: python
python: 
  - "3.4"
addons:
  apt:
     packages:
       - python3-dev
       - freetds-dev
install:
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py runserver