sudo: required
language: python
python: 
  - "3.4"
install:
  - sudo apt-get install python3-dev freetds-dev
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py runserver