sudo: false
language: python
python: 
  - "3.4"
addons:
  apt:
     packages:
       - python3-dev
       - freetds-dev
install:
  - sudo apt-get install python3-dev freetds-dev
  - pip install -r requirements.txt
script:
  - python manage.py migrate
  - python manage.py runserver